#!/bin/bash

# Generate expanded 3proxy configuration with 50 IPv4 proxies

OUTPUT_FILE="3proxy-expanded.cfg"

cat > "$OUTPUT_FILE" << 'EOF'
# 3proxy configuration - Expanded pool (50 proxies)
# Generated by generate-proxy-config.sh

# Logging
log /home/idlemat/htdocs/idlemat.es/logs/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

# Authentication (none for localhost)
auth none

# Allow from localhost only  
allow *

# Network interfaces
internal 0.0.0.0
external 0.0.0.0

# Max connections per proxy
maxconn 100

# Timeouts
timeouts 30 60 300 30

# Proxy instances - IPv4 (50 proxies on ports 9000-9049)
EOF

# Generate 50 SOCKS5 proxy instances
for port in {9000..9049}; do
    echo "socks -p${port}" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "# Total proxies: 50 IPv4" >> "$OUTPUT_FILE"
echo "# Port range: 9000-9049" >> "$OUTPUT_FILE"

echo "✅ Generated $OUTPUT_FILE with 50 proxies"
echo "📊 Proxy configuration:"
echo "   - IPv4 proxies: 50 (ports 9000-9049)"
echo "   - Total capacity: ~250-500 concurrent accounts"
echo ""
echo "To use this configuration:"
echo "   1. sudo cp $OUTPUT_FILE 3proxy.cfg"
echo "   2. ./stop.sh"
echo "   3. ./start.sh"
